#pragma config(Motor,  port2,           rightMotor,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[port2] = -127;
	motor[port3] = 127;
	wait1Msec(2300);

	motor[port2] = -127;
	motor[port3] = -127;
	wait1Msec(625);

	motor[port2] = -127;
	motor[port3] = 127;
	wait1Msec(2300);

	motor[port2] = -33;
	motor[port3] = 33;
	wait1Msec(2300);

	motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(625);

	motor[port2] = -123;
	motor[port3] = 123;
	wait1Msec(2300);

	motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(625);

	motor[port2] = -127;
	motor[port3] = 127;
	wait1Msec(2300);
}
